# Configurations for this project

classes: ['kicking', 'punching', 'pushing', 'neutral'] 


features:
  window_size: 5 # Number of adjacent frames for extracting features. 
  add_augmentation: False #For adding data augmentation

combine_skeletons_info.py:
  input:
    # A folder of skeleton jsons.
    detected_skeletons_folder: &skels_folder data_proc/ut_interaction
  output:
    # One txt containing all valid skeletons.
    all_skeletons_txt: &skels_txt data_proc/skeletons_data.txt
 
preprocessing_features.py:
  input: 
    all_skeletons_txt: *skels_txt
  output:
    processed_features: &features_x data_proc/features_X.csv
    processed_features_labels: &features_y data_proc/features_Y.csv

train.py:
  input:
    processed_features: *features_x
    processed_features_labels: *features_y
  output:
    model_path: models/trained_classifier.pickle

test.py:
  # Use command line arguements (examples are mentioned in README.md)
  # output is stored in output folder
  settings:
    
    source:
      webcam_max_framerate: 10.0
      video_sample_interval: 1


    alphapose:
      model: #TODO
      img_size: # TODO 656x368 #432x368
 
    # TODO
    display:
      desired_rows: 480 
  
  output:
    video_name: "video.avi" # save the resultant video to file
    video_fps: 10.0 # at what frame rate to write the output video
    skeleton_folder_name: "skeletons/"


image_filename_format: "{:05d}.jpg"
skeleton_filename_format: "{:05d}.txt"
